### ISSUE TITLE
TCOPFLOW Python Bindings Continued

### ISSUE THREAD

**Issue by jaelynlitz** [pnnl/ExaGO#140]
**Issue type**
- [X] New feature
- [ ] Bug
- [ ] Discussion
- [ ] Other

**Relates to**
- [ ] OPFLOW
- [ ] SOPFLOW
- [ ] SCOPFLOW
- [X] TCOPFLOW
- [ ] CMake build system
- [ ] Spack configuration
- [ ] Manual
- [ ] Web docs
- [X] Other - python bindings

**Summary**

In #131, we started outlining the python bindings for TCOPFLOW, and an initial test is passing!

@Jayapreethi will fill out the remaining steps - 

Still left to port are the functions: 
- [ ] function1.....

Tests still to write:
- [ ] hiop as solver

**Comment by cameronrutherford** [comment]
I am noticing that IPOPT is the only solver configured for TCOPFLOW, and in addition to that, TCOPFLOW is a little behind since we don't support ExaGOOptions for that.

@abhyshr can you clarify if more tests are necessary? It also seems like all TCOPFLOW functions are ported to python, so is there additional functionality we should look to add instead?

**Comment by abhyshr** [comment]
I think the bindings are sufficient for now. I am going to start working on updating the TCOPFLOW code and may ask more pythong bindings. For now, it looks good.
