### ISSUE TITLE
[SCOPFLOW] branch contingencies ignored based on to-from bus indices

### ISSUE THREAD

**Issue by tabholt** [pnnl/ExaGO#26]
ExaGO/src/ps/psreaddata.cpp : 899 there is a section of code that swaps branch indices so that the smaller bus index becomes from and the larger to. If contingencies do not match this convention they are ignored by ExaGO, even if the indices are as they appear in the original case file.

**Comment by abhyshr** [comment]
You are right, all contingencies that have from bus `fbus` greater than to bus `tbus` are being ignored because of the reordering of the from and to end ends that you point above. I believe this requires a one line fix in the `PSGetLine` function [here](https://github.com/pnnl/ExaGO/blob/2a20d5c225b1899018b405c726de8f7089cce9dd/src/ps/ps.cpp#L282).

We need to add check for reversed ends as well, i.e.,
Instead of 
`if (supplines[i]->fbus == fbus && supplines[i]->tbus == tbus)` 
use
`if ((supplines[i]->fbus == fbus && supplines[i]->tbus == tbus) || 
       (supplines[i]->reversed_ends & (supplines[i]->fbus == tbus && supplines[i]->tbus == fbus))`

I think this should fix this issue. Can you try it out and see if it works.
